### ISSUE TITLE
need to create the file lazymark.nvim in the cache folder 

### ISSUE THREAD

**Issue by vsedov** [LintaoAmons/lazymark.nvim#1]
Hi , nice little plugin, like your self I found my self having a similar issue, such that I found this a rather nice little plugin. 

Although, I had to create a lazymark.nvim in the cache folder and then enter some dummy data for this to actually work, as it would initially error out

**Comment by LintaoAmons** [comment]
I didn't notice that~ 

I shall find time to fix it ~ 

Currently a little busy

**Comment by vsedov** [comment]
Yeah I understand, if i have time, il try fixing it my self and make a pr later this week.

**Comment by LintaoAmons** [comment]
I have changed the persistence logic, guess the problem no longer exists

**Comment by vsedov** [comment]
Yep Looks good , thanks mate.
